package task

import (
	"time"

	"github.com/google/uuid"
)

type TaskState int

const (
	TaskPending TaskState = iota
	TaskRunning
	TaskCompleted
	TaskFailed
)

type Task struct {
	ID          uuid.UUID // Unique task identifier (generated by Manager)
	Name        string    // User-friendly name
	Image       string    // Container image to run
	State       TaskState // Current lifecycle state
	ContainerID string    // Docker container ID (populated once running)
	WorkerID    uuid.UUID // Assigned worker (set by scheduler)
	Error       string    // Error message if failed
	CreatedAt   time.Time
	StartedAt   time.Time
	FinishedAt  time.Time
}

func NewTask(name, image string) *Task {
	return &Task{
		ID:        uuid.New(),
		Name:      name,
		Image:     image,
		State:     TaskPending,
		CreatedAt: time.Now(),
	}
}
